version: '3.7'

services:
  app:
    image: 397937426503.dkr.ecr.us-east-2.amazonaws.com/nileanchor:${IMAGE_TAG:-latest}
    ports:
      - 3000:80
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 5s

  server:
    image: 397937426503.dkr.ecr.us-east-2.amazonaws.com/nileanchor/proxy:${IMAGE_TAG:-latest}
    environment:
      NODE_ENV: production
    ports:
      - 3001:3001
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 5s
